config/routes.rb
EasyFunds::Application.routes.draw do
  get "campaign/view"

  get "campaign/confirm"

  get "home/index"

  get "campaign/:id", :to => 'campaign#view', :as => 'view_campaign'

  post "campaign/:id", :to => 'campaign#request_checkout', :as => 'request_checkout'

  get "campaign/confirm", :to => "campaign#confirm", :as => 'confirm'

  root :to => 'home#index'
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  attr_accessible :amount, :date_due, :description, :status, :title, :organizer_id, :image_url

  belongs_to :organizer
  has_many :donations

  after_save :perform_transfers

  def total_donations
    self.donations.map(&:amount).sum.to_f
  end

  def self.check_expiration
    campaign = where(status: false)
    campaign.each do |campaign|
      if campaign.date_due  <= DateTime.now
        campaign.status = true
        campaign.save
      end
    end
  end

  def final_ratio
    ratio = (self.total_donations*100 / self.amount)

    if ratio > 100
      ratio = 100
    end

    ratio
  end

  def perform_transfers
    if (self.status == true)
      direct_pay = MPower::DirectPay.new

      self.donations.each do |donation|

        direct_pay.credit_account(donation.mpower_email,donation.amount.to_f)
        if self.total_donations < amount
          SmsghSms.push(:to => donation.mpower_phone, :msg => "Hello " + donation.name + ", Unfortunately, the target for " + donation.campaign.title + " wasn't reached. " + donation.amount.to_f.to_s + " GHS was refunded back to your MPower account.")
        else
          SmsghSms.push(:to => donation.mpower_phone, :msg => "Hello " + donation.name + ", Thank you for your donation to support " + donation.campaign.title + ". The total amount raised was " + self.total_donations.to_f.to_s + " GHS.")
        end

      end

      if self.total_donations < amount
        SmsghSms.push(:to => donation.campaign.organizer.phone, :msg => "Hello " + donation.campaign.organizer.name + ", Unfortunately, the target for " + donation.campaign.title + " wasn't reached. " + self.total_donations.to_f.to_s + "GHS out of " + donation.campaign.amount.to_f.to_s + " was raised and all donors were refunded.")
      end

    end
  end
  handle_asynchronously :perform_transfers

end

app/models/donation.rb
class Donation < ActiveRecord::Base
  attr_accessible :amount, :mpower_email, :mpower_phone, :name, :campaign_id

  validates :amount, :presence => true
  belongs_to :campaign
  validates :amount, :numericality => :true
  validates :amount, :numericality =>{:greater_than=>0, :message=>"Please enter amount greater than 0.00GHS"}

end

app/models/organizer.rb
class Organizer < ActiveRecord::Base
  attr_accessible :address, :email, :name, :phone

  has_many :campaigns
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/campaign_controller.rb
class CampaignController < ApplicationController
  def view
    @campaign = Campaign.find(params[:id])

    @donation = Donation.new
  end

  def request_checkout
    @donation = Donation.new(params[:donation])

    @donation.campaign = Campaign.find(params[:id])

    if @donation.valid?

      invoice = MPower::Checkout::Invoice.new
      invoice.add_item(@donation.campaign.title,1,@donation.amount,@donation.amount);
      invoice.description = "Donation to support " + @donation.campaign.title;
      invoice.total_amount = @donation.amount.to_f
      invoice.add_custom_data("CampaignID",@donation.campaign.id);
      invoice.return_url = confirm_url(@campaign)
      invoice.create
      redirect_to invoice.invoice_url

    else
      @campaign = Campaign.find(params[:id])
      render 'view'
    end
  end

  def confirm
    token = params[:token]

    invoice = MPower::Checkout::Invoice.new
    if invoice.confirm(token)

      @donation = Donation.new
      @donation.amount = invoice.total_amount
      @donation.name = invoice.get_customer_info "name"
      @donation.mpower_email = invoice.get_customer_info "email"
      @donation.mpower_phone = invoice.get_customer_info "phone"
      @donation.campaign = Campaign.find(invoice.get_custom_data "CampaignID")
      @donation.save
      flash[:notice] = "Thank you, " + @donation.name + " for supporting " + @donation.campaign.title + " with " + @donation.amount.to_f.to_s + " GHS!"
      redirect_to root_url
    end

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  	@campaigns = Campaign.where(:status => false)

  	respond_to do |format|
    	format.html # index.html.erb
    	format.json  { render :json => @campaigns }
  end

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaign_helper.rb
module CampaignHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/campaign/confirm.html.erb
<h1>Campaign#confirm</h1>
<p>Find me in app/views/campaign/confirm.html.erb</p>

app/views/campaign/view.html.erb
  <% provide(:title, 'EasyFunds | ' + @campaign.title) %>
<br />
 <div class="row">
 	<div class="large-6 columns">
 		<%= image_tag @campaign.image_url, :style => "border:1px solid silver;" %>
 	</div>
 	<div class="large-6 columns">
 		
 		

 		
 		

		<div class="section-container auto" data-section>
  <section class="active">
    <p class="title" data-section-title><a href="#panel1">Description</a></p>
    <div class="content" data-section-content>
     <h4><%= @campaign.title %></h4>
 		<p><%= @campaign.description %></p>

    </div>
  </section>
  <section>
    <p class="title" data-section-title><a href="#panel2">Organizer</a></p>
    <div class="content" data-section-content>
    <p>Name: <%= @campaign.organizer.name %><br />
 		Address: <%= @campaign.organizer.address %><br />
 		Email: <%= @campaign.organizer.email %><br />
		Phone: <%= @campaign.organizer.phone %></p>
    </div>
  </section>
</div>

 	</div>
 </div>
 <br /><hr />
 <div class="row">
 	<div class="large-6 columns">
 		<!-- raised amount / target amount goes here -->
 		<h6><%= @campaign.total_donations %> GHS raised out of <%= @campaign.amount %> GHS</h6>
 	</div>
 	<div class="large-6 columns">
 		<%= simple_form_for @donation, :url => request_checkout_url do |f| %>
  <%= f.input :amount, :label => false, :placeholder => "Enter an amount here"  %>
  <%= f.submit "Donate", :class => "button" %>
<% end %>
 	</div>
 	
 </div>

app/views/home/index.html.erb
 <% provide(:title, 'EasyFunds | Home') %>

<% for campaign in @campaigns %>

<div class="large-4 columns left">
	<ul class="pricing-table">
    <li class="description"><%= link_to (image_tag (campaign.image_url)), view_campaign_url(campaign) %></li>
  <li class="title"><%= campaign.title %></li>
   <li class="description"><div class="progress success round"><%= "<span class='meter' style='width:".html_safe + campaign.final_ratio.to_f.to_s + "%'></span>".html_safe %></div></li>
  <li class="bullet-item">Date Due: <%= campaign.date_due.strftime("%d %B %Y") %></li>
 
</ul>
</div>
<% end %>
<!--
<div class="large-4 columns">
	<ul class="pricing-table">
  <li class="title">Title</li>
  <li class="price">100000</li>
  <li class="description">Description</li>
  <li class="bullet-item">Organizer Name</li>
 
  <li class="cta-button"><a class="small button" href="#">Support Cause</a></li>
</ul>
</div>

<div class="large-4 columns">
	<ul class="pricing-table">
  <li class="title">Title</li>
  <li class="price">100000</li>
  <li class="description">Description</li>
  <li class="bullet-item">Organizer Name</li>
 
  <li class="cta-button"><a class="small button" href="#">Support Cause</a></li>
</ul>
</div>

<div class="large-4 columns">
	<ul class="pricing-table">
  <li class="title">Title</li>
  <li class="price">100000</li>
  <li class="description">Description</li>
  <li class="bullet-item">Organizer Name</li>
 
  <li class="cta-button"><a class="small button" href="#">Support Cause</a></li>
</ul>
</div>

<div class="large-4 columns">
	<ul class="pricing-table">
  <li class="title">Title</li>
  <li class="price">100000</li>
  <li class="description">Description</li>
  <li class="bullet-item">Organizer Name</li>
 
  <li class="cta-button"><a class="small button" href="#">Support Cause</a></li>
</ul>
</div>

<div class="large-4 columns">
	<ul class="pricing-table">
  <li class="title">Title</li>
  <li class="price">100000</li>
  <li class="description">Description</li>
  <li class="bullet-item">Organizer Name</li>
 
  <li class="cta-button"><a class="small button" href="#">Support Cause</a></li>
</ul>
</div>-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  <%= render 'shared/head' %>
  </head>

  <body>
   <%= render 'shared/banner' %>

  <br />
    <div class="row">
      <div class="large-12 columns">
         <!-- campaign runinng goes here -->
          <%= yield %>
      </div>
     
    </div>
  

   <%= render 'shared/footer' %>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<%= render 'shared/head' %>
  </head>

  <body>
		

		<%= render 'shared/banner' %>

   	
  <div class="bg">  
   <% if flash[:notice] %>
      <div data-alert class="alert-box success" style="text-align:center;">
            <%= flash[:notice] %>
          <a href="#" class="close">&times;</a>
      </div>

    <% end %>  
    <div class="row">
      <div class="large-12 columns">
         <!-- campaign runinng goes here --><br />
          <%= yield %>
      </div>
     
    </div>
    </div>

	<!--<div class="bg" style="border-top:2px solid black;">
    <div class="row">
      <div class="large-12 columns">
      	<br />
        <h4 style="text-align:center;">FAQ</h4>

        <h6 style="text-align:center;">What kind of causes can I support?</h6>
        <p style="text-align:center;">EasyFunds supports a variety of causes such as fundraisers for orphanages, kickstart campaigns for busineses, and even fun events like raising money for a fantasy trip.</p>

         <h6 style="text-align:center;">Can I donate more than once?</h6>
        <p style="text-align:center;">Absolutely, you can donate as many times as you want. The more donations you make, the faster the campaign goal will be reached.</p>

         <h6 style="text-align:center;">What happens when a campaign target is not reached?
        </h6>
        <p style="text-align:center;">When a campaign target is not reached, all donors are refunded with the amount they donated.</p>
      </div>
    </div>
    </div>-->

   <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_banner.html.erb
<div class="bg_main">
      <div class="row">
        <div class="large-6 columns large-centered">
        	<br />
            <%= link_to (image_tag "logo.png"), root_url %>
          <br />
        </div>
        <br /><br /><br /><br />
        <div class="large-12 columns large-centered">
         <h1 style="text-align:center;font-weight:900; color:white;text-shadow: 0px 0px 5px #000">SUPPORT CAUSES YOU CARE ABOUT!</h1>
          <p style="text-align:center; font-size:22px; color:white;text-shadow: 0px 0px 5px #000">EasyFunds allows you to find and support causes that matters to you. From social fundraisers to kickstarter campaigns, there are a variety of causes to support.</p>
        </div>
    </div>
    </div>

app/views/shared/_footer.html.erb
  <div style="background-color:black;;">
    <div class="row">
      <div class="large-12 columns">
       <p style="font-size:12px; text-align:center; color:white;margin-top:10px;">FAQ | Blog<br />All Rights Reserved &copy; 2013 EasyFunds<br />Built by <a href="https://www.twitter.com/edemkumodzi" target="_blank">Edem</a>, <a href="https://twitter.com/philip_nunoo" target="_blank">Philip</a> & <a href="https://twitter.com/Humph_Pietersen" target="_blank">Humphrey</a> </p>
      </div>
    </div>
    </div>


    
    <%= javascript_include_tag "application" %>

app/views/shared/_head.html.erb
  <meta charset="utf-8" />

    <!-- Uncomment to make IE8 render like IE7 -->
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

    <!-- Set the viewport width to device width for mobile -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
   <link href='http://fonts.googleapis.com/css?family=Lato:400,700,900' rel='stylesheet' type='text/css'>